### ISSUE TITLE
Download links unavailable for items in a bundle

### ISSUE THREAD

**Issue by mindctrl** [wpninjas/edd-git-download-updater#19] opened 2015-09-04 20:10 UTC
When purchasing a bundle that includes a product whose files are configured for git, the download links aren't visible on the receipt unless you manually specify a file name on the individual product. The placeholder doesn't show up.

Steps to reproduce:
- create a single product, attach it to your git tag, and leave the file name as the placeholder. [screenshot](http://cl.ly/image/3F0C03343h0L)
- create a bundle and select the single product created in the previous step
- purchase the bundle

At this point you'll see the links for the files aren't there. That's because the title is missing on the link. [screenshot](http://cl.ly/image/1C1k1w1q2b0y). 

Now, go back to the single product, supply a file name and update, then go back and refresh the confirmation page. The link will be visible.

**Comment by kstover** [comment] 2015-09-06 19:44
This is a known issue. I think we have a fix in the pipe, but it needs more testing.

**Comment by mindctrl** [comment] 2015-09-25 21:06
@kstover need any help testing this? It's biting us regularly.

**Comment by kstover** [comment] 2015-10-02 01:46
@mindctrl Thanks for the offer! We can definitely recreate this on our own site as well. The problem is having enough development time to fix it. I'm going to try and track it down this weekend.

**Comment by KienTrong** [comment] 2016-01-07 08:06
@kstover Purchased this add-on via EDD add-on market and has the same issue, do you guys have any update status?

**Comment by cklosowski** [comment] 2016-05-09 22:32
I think this is actually a core EDD bug in the receipt logic for iterating over the files for a receipt or the download history shortcode. Currently non-bundle products on the receipt use the `edd_get_file_name( $file )` to get the filename which has a fallback if the filename is empty, where as the bundle uses the array item directly to display the name, which in this case is blank.

For the `Download History` shortcode, we're always using the array key `name` directly, instead of the helper function. I'm going to open an issue in EDD 2.6 for this, and release it there, and if that clears it up for people we can close this out.

**Comment by cklosowski** [comment] 2016-05-09 23:16
I've got a PR for the EDD Side of things, but I think I'm going to also do a 'fallback' in saving a file so that we're always adding a file name

**Comment by cklosowski** [comment] 2016-05-09 23:36
Ok I found another issue here, and it's that if you `Fetch` the new Git version, and then `Update` the post, the data you fetched is being blanked in the `Name` section.

**Comment by cklosowski** [comment] 2016-05-10 01:32
@pippinsplugins @kstover I've got differing opinions of the 'name' field. EDD core requires a name be supplied. The issue we have here (and that causes blank `name` entries) is if you use the `fetch`, EDD Git Updater uses either the provided name, and then if that's empty falls back to the `file name`, then if you `Update` the post, it wipes that out since EDD sees that it's empty.

This is where we've got the oddness.

We can update EDD to make sure we always use the fallback function `edd_get_file_name()`, and we can make EDD Git Updater force the `name` to always be something, but this means the flow would be if someone decides to leave the `name` field blank for the EDD Git Updater, upon `update` it would be filled with the default name, and not using the placeholder.

What are your thoughts on this guys?

**Comment by pippinsplugins** [comment] 2016-05-10 02:26
I vote we make EDD use `edd_get_file_name()` and make this plugin set a name.

**Comment by cklosowski** [comment] 2016-05-10 03:31
Ok, so basically if no name is entered, generate a name automatically and save it, so it's never blank after saving. I'm for that too.

**Comment by cklosowski** [comment] 2016-05-10 08:12
@mindctrl @kstover @pippinsplugins This could use a little testing, PR is open for review.

**Comment by kstover** [comment] 2016-05-10 14:11
@cklosowski Agreed. My testing shows this working fine.

**Comment by mindctrl** [comment] 2016-05-10 14:26
@cklosowski fixed the bundle links after I went back and edited the product. I'm seeing all sorts of PHP debug notices, but I don't think they're related to this.

**Comment by cklosowski** [comment] 2016-05-10 14:31
@mindctrl ok i'll work with you to verify they are unrelated

**Comment by pippinsplugins** [comment] 2016-05-10 14:38
Assuming php notices are unrelated, let's please get this deployed :)

**Comment by cklosowski** [comment] 2016-05-10 14:53
sounds good!

**Comment by kstover** [comment] 2016-05-10 14:57
Once you guys give me the ok, I'll get a new version tagged and released.

**Comment by cklosowski** [comment] 2016-05-10 15:01
@kstover I can take care of it if need be, freeing you up to keep doing Ninja type things :)

**Comment by cklosowski** [comment] 2016-05-10 15:01
Looks like this caused a merge conflict, I'll fix that up too.

**Comment by kstover** [comment] 2016-05-10 15:13
Ha! Thanks. I merged the other relevant PRs.

**Comment by kstover** [comment] 2016-05-10 15:13
Remind me to buy you a beer the next time we're in the same locale, @cklosowski. :)

**Comment by mindctrl** [comment] 2016-05-10 16:50
This is working for me. The other errors I mentioned above are unrelated and only on the one test site. Confirmed it's working fine on another site.

**Comment by cklosowski** [comment] 2016-05-10 17:01
Thanks @mindctrl I'm going to merge this and do some final testing and then get a release ready.

**Closed** 2016-05-10 17:04 UTC
Labels: bug
